name: Deploy to Cloud Storage
on:
push:
 branches:
   - main
jobs:
deploy:
 runs-on: ubuntu-latest
 steps:
   - name: Checkout code
     uses: actions/checkout@v3
   - name: Authenticate to Google Cloud
     uses: google-github-actions/auth@v1
     with:
       credentials_json: ${{ secrets.GCP_SA_KEY }}
   - name: Set up Cloud SDK
     uses: google-github-actions/setup-gcloud@v1
     with:
       project_id: myposdata
   - name: Install Node.js
     uses: actions/setup-node@v3
     with:
       node-version: '22'
   - name: Install Dependencies
     run: npm install
   - name: Build JSX Files
     run: npm run build
   - name: Deploy to Cloud Storage
     run: |
       gsutil -m cp -r index.html lib styles.css tailwind.css favicon.ico dist gs://syjpmopmh-pos-web/
       gsutil -m acl ch -r -u AllUsers:R gs://syjpmopmh-pos-web/
       gsutil -m setmeta -h "Cache-Control:no-cache, max-age=0" gs://syjpmopmh-pos-web/dist/*.js
       gsutil -m setmeta -h "Cache-Control:no-cache, max-age=0" gs://syjpmopmh-pos-web/index.html
       gsutil web set -m index.html -e index.html gs://syjpmopmh-pos-web/
