name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.17.0'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Upload to Google Cloud Storage
      uses: google-github-actions/upload-cloud-storage@v2
      with:
        path: .
        destination: syjpmopmh-pos-web
        glob: |
          index.html
          dist/*.js
          styles.css
          tailwind.css
          favicon.ico
          lib/*.js
          lib/*.css
        headers: |
          Cache-Control: no-cache, max-age=0

    - name: Set public ACL
      run: |
        gsutil acl ch -u AllUsers:R gs://syjpmopmh-pos-web/index.html
        gsutil acl ch -u AllUsers:R gs://syjpmopmh-pos-web/dist/app.js
        gsutil acl ch -u AllUsers:R gs://syjpmopmh-pos-web/dist/dashboardSalesTable.js
        gsutil acl ch -u AllUsers:R gs://syjpmopmh-pos-web/styles.css
        gsutil acl ch -u AllUsers:R gs://syjpmopmh-pos-web/tailwind.css
        gsutil acl ch -u AllUsers:R gs://syjpmopmh-pos-web/favicon.ico
        gsutil acl ch -u AllUsers:R gs://syjpmopmh-pos-web/lib/react.min.js
        gsutil acl ch -u AllUsers:R gs://syjpmopmh-pos-web/lib/react-dom.min.js
        gsutil acl ch -u AllUsers:R gs://syjpmopmh-pos-web/lib/flatpickr.min.js
        gsutil acl ch -u AllUsers:R gs://syjpmopmh-pos-web/lib/flatpickr.min.css

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.17.0'
        cache: 'npm'

    - name: Install backend dependencies
      run: npm ci
      working-directory: ./server

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Cloud Functions
      uses: google-github-actions/deploy-cloud-functions@v2
      with:
        name: sales
        runtime: nodejs22
        region: us-central1
        source_dir: ./server
        entry_point: sales
        http_trigger: true
        allow_unauthenticated: true