name: Deploy to Cloud Run and GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Authenticate with Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/myposdata/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'syjpmopmh-pos-web@myposdata.iam.gserviceaccount.com'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - name: Configure Docker
      run: gcloud auth configure-docker
    - name: Build and Push Docker Image
      run: |
        docker build -t gcr.io/myposdata/sy-jpm-pos-web .
        docker push gcr.io/myposdata/sy-jpm-pos-web
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy sy-jpm-pos-web \
          --image gcr.io/myposdata/sy-jpm-pos-web \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --service-account syjpmopmh-pos-web@myposdata.iam.gserviceaccount.com \
          --set-env-vars GOOGLE_CLOUD_PROJECT=myposdata
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
    - name: Verify Deployment
      run: |
        curl https://sy-jpm-pos-web-uc.a.run.app/health